defmodule Newsticker.Repo.Migrations.SourceNameNullable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ticker_sources) do
      modify :name, :text, null: true
    end
  end

  def down do
    alter table(:ticker_sources) do
      modify :name, :text, null: false
    end
  end
end
