defmodule Newsticker.Repo.Migrations.TickerSourceUriIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:ticker_sources, [:uri], name: "ticker_sources_uri_index")
  end

  def down do
    drop_if_exists unique_index(:ticker_sources, [:uri], name: "ticker_sources_uri_index")
  end
end
