defmodule Newsticker.Repo.Migrations.AddTickerSite do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ticker_sources) do
      add :site_id, :uuid
    end

    create table(:ticker_sites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:ticker_sources) do
      modify :site_id,
             references(:ticker_sites,
               column: :id,
               name: "ticker_sources_site_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:ticker_sites) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:ticker_sites) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:ticker_sources, "ticker_sources_site_id_fkey")

    alter table(:ticker_sources) do
      modify :site_id, :uuid
    end

    drop table(:ticker_sites)

    alter table(:ticker_sources) do
      remove :site_id
    end
  end
end
